print("Olá, mundo!")
Nome = input("Qual seu nome? \n")
print("Ah, então seu nome é:", Nome)
Idade = input("E qual a sua idade, %s? \n" % (Nome))
print("Olá %s, você tem %s anos de idade >_<" % (Nome, Idade))
Numero = int(input("Me informe um número: \n"))
print("O número fornecido foi:", Numero)
print("Me envie três números para serem somados: \n")
Numero1 = float(input())
Numero2 = float(input())
Numero3 = float(input())
print("A soma dos três números é: ", Numero1 + Numero2 + Numero3)
print("A soma entre o número %.1f e o número %.1f é:" % (Numero1, Numero2), Numero1 + Numero2)
print("A média entre os 3 números fornecidos é:", (Numero1 + Numero2 + Numero3) / 3)